### ISSUE TITLE
找不到'uws' module , 安装了也找不到

### ISSUE THREAD

**Issue by franklen** [weihomechen/blog-node#2]
pts] 2019-05-12 09:55:24,520 ERROR 7025 [app_worker] exit with code:1
[egg-scripts] internal/modules/cjs/loader.js:615
[egg-scripts]     throw err;
[egg-scripts]     ^
[egg-scripts] 
[egg-scripts] Error: Cannot find module 'uws'
[egg-scripts]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)
[egg-scripts]     at Function.Module._load (internal/modules/cjs/loader.js:539:25)
[egg-scripts]     at Module.require (internal/modules/cjs/loader.js:667:17)
[egg-scripts]     at require (internal/modules/cjs/helpers.js:20:18)
[egg-scripts]     at Server.init (/home/ubuntu/blog/blog-node/node_modules/engine.io/lib/server.js:107:28)
[egg-scripts]     at new Server (/home/ubuntu/blog/blog-node/node_modules/engine.io/lib/server.js:65:8)
[egg-scripts]     at Function.attach (/home/ubuntu/blog/blog-node/node_modules/engine.io/lib/engine.io.js:123:16)
[egg-scripts]     at Server.initEngine (/home/ubuntu/blog/blog-node/node_modules/socket.io/lib/index.js:310:21)
[egg-scripts]     at Server.listen.Server.attach (/home/ubuntu/blog/blog-node/node_modules/socket.io/lib/index.js:284:10)
[egg-scripts]     at Application.app.on.server (/home/ubuntu/blog/blog-node/node_modules/egg-socket.io/lib/io.js:131:12)
[egg-scripts]     at Application.emit (events.js:202:15)
[egg-scripts]     at startServer (/home/ubuntu/blog/blog-node/node_modules/egg-cluster/lib/app_worker.js:66:7)
[egg-scripts]     at process.nextTick (/home/ubuntu/blog/blog-node/node_modules/get-ready/index.js:73:53)

**Comment by weihomechen** [comment]
看了下我本地可以装上，这个是用于`websocket`的，`egg`默认使用了`ws `引擎，你可以把这个`uws`去掉
